### ISSUE TITLE
Failed to activate the linter-raml-myrules package

### ISSUE THREAD

**Issue by eduardosponda** [ramltribute/linter-raml-myrules#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-raml-myrules](https://github.com/ramltribute/linter-raml-myrules) package 0.0.6

### Stack Trace

Failed to activate the linter-raml-myrules package

```
At require.cache.hasOwnProperty is not a function

TypeError: require.cache.hasOwnProperty is not a function
    at Object.activate (/packages/linter-raml-myrules/lib/linter-raml.js:25:31)
    at Package.activateNow (~/AppData/Local/atom/app-1.28.2/resources/app/src/package.js:230:33)
    at measure (~/AppData/Local/atom/app-1.28.2/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.28.2/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.28.2/resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.28.2/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.28.2/resources/app/src/package-manager.js:695:42)
    at ~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.28.2/resources/app/src/buffered-process.js:267:15)
    at ChildProcess.process.on (~/AppData/Local/atom/app-1.28.2/resources/app/src/buffered-process.js:297:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
  4x -4:03.8.0 core:backspace (input.hidden-input)
     -4:00.8.0 core:confirm (input.hidden-input)
 14x -3:59.6.0 core:backspace (input.hidden-input)
     -3:57.6.0 core:confirm (input.hidden-input)
 15x -3:47.8.0 core:backspace (input.hidden-input)
     -3:46 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
api-workbench 0.8.48 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-raml 1.0.1 
linter-raml-myrules 0.0.6 
linter-ui-default 1.7.1 
raml 0.2.0 
raml-snippets 0.1.0 
```

**Comment by djafaka** [comment]
The error was thrown from the linter-raml-myrules package. This issue has already been reported.

Failed to activate the linter-raml-myrules package

require.cache.hasOwnProperty is not a function
Hide Stack Trace
TypeError: require.cache.hasOwnProperty is not a function
    at Object.activate (/Users/karim.djaafar/.atom/packages/linter-raml-myrules/lib/linter-raml.js:25:31)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3421604)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3421016)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3418626)
    at activationPromise.activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3420876)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3420819)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381612)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:935623
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:930229)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1127206)
    at e.bufferStream (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1127294)
    at Socket.e.on (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1125962)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close [as _onclose] (net.js:596:12)

**Comment by sandroquintana** [comment]
1. Install Atom
2. Install api-workbench
3. Istall linter-raml-myrules
